version: "3.9"

networks:
    fastapi_demo_network:

services:
    database:
        image: "mysql:5.7.34"
        container_name: "${mysql_container_name}"
        # command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - "${mysql_port}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: admin

        networks:
            - fastapi_demo_network
