name: Continuous integration
on: [push]

jobs:
  run_inserts_count_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'
      - name: install dependencies
        run: |
          pip install invoke gitpython
      - name: run inserts count check
        run: invoke tests.inserts-count-check

  run_commit_stage_in_container:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
      - name: Build docker container
        uses: docker/build-push-action@v2
        with:
          tags: puchatek_w_szortach/fastapi_demo:latest
          file: ./docker/app.Dockerfile
      - name: debugging
        run: |
          docker run --rm -v $PWD:/app puchatek_w_szortach/fastapi_demo:latest ls
      - name: debugging 2
        run: |
          docker run --rm -v $PWD:/app puchatek_w_szortach/fastapi_demo:latest invoke --list
      # - name: run commit stage tests
      #   run: |
      #     docker run --rm -v $PWD:/app puchatek_w_szortach/fastapi_demo:latest invoke tests.commit-stage
